=== carlocek/raspberry-communication-VxWorks/WorkspaceOris/App1/TCAnalyzer/TPN_graph.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
ORIS - framework for editing/analysis/simulation of Time Petri Nets
developed by Dipartimento di Sistemi e Informatica - University of
Firenze
- Italy
G.Bucci, A.Fedeli, E.Vicario
{bucci, fedeli, vicario}@dsi.unifi.it
Original DTD file improved by F.Poli
poli@dsi.unifi.it
-->

<!-- Grafo -->
<!ELEMENT Grafo (not_explored_state+,class+)>
<!ATTLIST Grafo
	name CDATA #REQUIRED 
	level CDATA #REQUIRED 
	state CDATA #REQUIRED
>

<!-- Not explored states -->
<!ELEMENT not_explored_state (nes*)>

<!-- Not explored state -->
<!ELEMENT nes EMPTY>	
<!ATTLIST nes
	id CDATA #REQUIRED
>

<!-- Class -->
<!ELEMENT class (place*,transx*,binding*,zone*)>
<!ATTLIST class
	level CDATA #REQUIRED
	id CDATA #REQUIRED
>

<!-- Place -->
<!ELEMENT place EMPTY>	
<!ATTLIST place
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	tokens CDATA #REQUIRED
>

<!-- Transx -->
<!ELEMENT transx EMPTY>	
<!ATTLIST transx
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	Progr (Yes|No) "Yes"
	New (Yes|No) "Yes"
	EFT CDATA #REQUIRED
	LFT CDATA #REQUIRED 	
	Fir (Yes|No) #REQUIRED
	class_dest CDATA #IMPLIED
	probability CDATA #IMPLIED
>

<!-- Binding -->
<!ELEMENT binding EMPTY>	
<!ATTLIST binding
	idtrans1 CDATA #REQUIRED
	idtrans2 CDATA #REQUIRED
	EFT CDATA #REQUIRED 
	LFT CDATA #REQUIRED
>

<!-- Zone -->
<!ELEMENT zone (constraint+,cross_constraint*)>
<!ATTLIST zone
	function CDATA #REQUIRED
>

<!-- Zone Constraint -->
<!ELEMENT constraint EMPTY>
<!ATTLIST constraint
	idtrans CDATA #REQUIRED
	A CDATA #REQUIRED
	B CDATA #REQUIRED
>

<!-- Zone Cross Constraint -->
<!ELEMENT cross_constraint EMPTY>
<!ATTLIST cross_constraint
	idtrans1 CDATA #REQUIRED
	idtrans2 CDATA #REQUIRED
	A CDATA #REQUIRED
	B CDATA #REQUIRED
>

=== carlocek/raspberry-communication-VxWorks/WorkspaceOris/App2/TCAnalyzer/output.xml
<?xml version="1.0"  encoding="ISO-8859-1" ?>
<!--
Automatically created by TimePetriNet StateSpaceExplorer
-->
<!DOCTYPE Grafo SYSTEM "TPN_graph.dtd">
<?xml-stylesheet type="text/xsl" href="TPN_graph.xsl"?>
<Grafo name="anonymous" level="1" state="101">
<not_explored_state>
</not_explored_state>
 <class level="0" id="0" >
   <place id="8" name="mem" tokens="1"/>
   <transx id="0" name="t0" Progr="Yes" New="Yes" EFT="  10" LFT="  10" Fir="Yes" class_dest="1"/>
   <transx id="10" name="t8" Progr="Yes" New="Yes" EFT="  20" LFT="  20" Fir="No "/>
   <transx id="14" name="t4" Progr="Yes" New="Yes" EFT="  10" LFT="  10" Fir="Yes" class_dest="2"/>
 </class>
 <class level="0" id="1" >
   <place id="0" name="p0" tokens="1"/>
   <place id="8" name="mem" tokens="1"/>
   <transx id="10" name="t8" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="14" name="t4" Progr="Yes" New="No " EFT="   0" LFT="   0" Fir="Yes" class_dest="3"/>
   <transx id="9" name="t1" Progr="Yes" New="Yes" EFT="   0" LFT="   0" Fir="Yes" class_dest="4"/>
   <transx id="0" name="t0" Progr="Yes" New="Yes" EFT="  10" LFT="  10" Fir="No "/>
 </class>
 <class level="0" id="2" >
   <place id="5" name="p4" tokens="1"/>
   <place id="8" name="mem" tokens="1"/>
   <transx id="0" name="t0" Progr="Yes" New="No " EFT="   0" LFT="   0" Fir="Yes" class_dest="5"/>
   <transx id="10" name="t8" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="5" name="t5" Progr="Yes" New="Yes" EFT="   0" LFT="   0" Fir="Yes" class_dest="6"/>
   <transx id="14" name="t4" Progr="Yes" New="Yes" EFT="  10" LFT="  10" Fir="No "/>
 </class>
 <class level="0" id="3" >
   <place id="0" name="p0" tokens="1"/>
   <place id="5" name="p4" tokens="1"/>
   <place id="8" name="mem" tokens="1"/>
   <transx id="9" name="t1" Progr="Yes" New="No " EFT="   0" LFT="   0" Fir="Yes" class_dest="7"/>
   <transx id="0" name="t0" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="10" name="t8" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="14" name="t4" Progr="Yes" New="Yes" EFT="  10" LFT="  10" Fir="No "/>
   <transx id="5" name="t5" Progr="No " New="Yes" EFT="   0" LFT="   0" Fir="No "/>
 </class>
 <class level="0" id="4" >
   <place id="4" name="p1" tokens="1"/>
   <place id="8" name="mem" tokens="1"/>
   <transx id="0" name="t0" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="10" name="t8" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="14" name="t4" Progr="Yes" New="No " EFT="   0" LFT="   0" Fir="Yes" class_dest="8"/>
   <transx id="1" name="t2" Progr="Yes" New="Yes" EFT="   0" LFT="   0" Fir="Yes" class_dest="9"/>
 </class>
 <class level="0" id="5" >
   <place id="0" name="p0" tokens="1"/>
   <place id="5" name="p4" tokens="1"/>
   <place id="8" name="mem" tokens="1"/>
   <transx id="10" name="t8" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="14" name="t4" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="9" name="t1" Progr="Yes" New="Yes" EFT="   0" LFT="   0" Fir="Yes" class_dest="7"/>
   <transx id="0" name="t0" Progr="Yes" New="Yes" EFT="  10" LFT="  10" Fir="No "/>
   <transx id="5" name="t5" Progr="No " New="No " EFT="   0" LFT="   0" Fir="No "/>
 </class>
 <class level="0" id="6" >
   <place id="6" name="p5" tokens="1"/>
   <place id="8" name="mem" tokens="1"/>
   <transx id="0" name="t0" Progr="Yes" New="No " EFT="   0" LFT="   0" Fir="Yes" class_dest="10"/>
   <transx id="10" name="t8" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="14" name="t4" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="6" name="t6" Progr="Yes" New="Yes" EFT="   0" LFT="   0" Fir="Yes" class_dest="11"/>
 </class>
 <class level="0" id="7" >
   <place id="5" name="p4" tokens="1"/>
   <place id="4" name="p1" tokens="1"/>
   <place id="8" name="mem" tokens="1"/>
   <transx id="0" name="t0" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="10" name="t8" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="14" name="t4" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="1" name="t2" Progr="Yes" New="Yes" EFT="   0" LFT="   0" Fir="Yes" class_dest="12"/>
   <transx id="5" name="t5" Progr="No " New="No " EFT="   0" LFT="   0" Fir="No "/>
 </class>
 <class level="0" id="8" >
   <place id="5" name="p4" tokens="1"/>
   <place id="4" name="p1" tokens="1"/>
   <place id="8" name="mem" tokens="1"/>
   <transx id="1" name="t2" Progr="Yes" New="No " EFT="   0" LFT="   0" Fir="Yes" class_dest="12"/>
   <transx id="0" name="t0" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="10" name="t8" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="14" name="t4" Progr="Yes" New="Yes" EFT="  10" LFT="  10" Fir="No "/>
   <transx id="5" name="t5" Progr="No " New="Yes" EFT="   0" LFT="   0" Fir="No "/>
 </class>
 <class level="0" id="9" >
   <place id="10" name="p2" tokens="1"/>
   <transx id="0" name="t0" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="10" name="t8" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="14" name="t4" Progr="Yes" New="No " EFT="   0" LFT="   0" Fir="Yes" class_dest="13"/>
   <transx id="11" name="t3" Progr="Yes" New="Yes" EFT="   1" LFT="   2" Fir="No "/>
 </class>
 <class level="0" id="10" >
   <place id="0" name="p0" tokens="1"/>
   <place id="6" name="p5" tokens="1"/>
   <place id="8" name="mem" tokens="1"/>
   <transx id="10" name="t8" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="14" name="t4" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="9" name="t1" Progr="Yes" New="Yes" EFT="   0" LFT="   0" Fir="Yes" class_dest="14"/>
   <transx id="0" name="t0" Progr="Yes" New="Yes" EFT="  10" LFT="  10" Fir="No "/>
   <transx id="6" name="t6" Progr="No " New="No " EFT="   0" LFT="   0" Fir="No "/>
 </class>
 <class level="0" id="11" >
   <place id="7" name="p6" tokens="1"/>
   <transx id="0" name="t0" Progr="Yes" New="No " EFT="   0" LFT="   0" Fir="Yes" class_dest="15"/>
   <transx id="10" name="t8" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="14" name="t4" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="7" name="t7" Progr="Yes" New="Yes" EFT="   1" LFT="   2" Fir="No "/>
 </class>
 <class level="0" id="12" >
   <place id="5" name="p4" tokens="1"/>
   <place id="10" name="p2" tokens="1"/>
   <transx id="0" name="t0" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="10" name="t8" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="14" name="t4" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="11" name="t3" Progr="Yes" New="Yes" EFT="   1" LFT="   2" Fir="Yes" class_dest="16"/>
   <transx id="5" name="t5" Progr="No " New="No " EFT="   0" LFT="   0" Fir="No "/>
 </class>
 <class level="0" id="13" >
   <place id="5" name="p4" tokens="1"/>
   <place id="10" name="p2" tokens="1"/>
   <transx id="11" name="t3" Progr="Yes" New="No " EFT="   1" LFT="   2" Fir="Yes" class_dest="16"/>
   <transx id="0" name="t0" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="10" name="t8" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="14" name="t4" Progr="Yes" New="Yes" EFT="  10" LFT="  10" Fir="No "/>
   <transx id="5" name="t5" Progr="No " New="Yes" EFT="   0" LFT="   0" Fir="No "/>
 </class>
 <class level="0" id="14" >
   <place id="6" name="p5" tokens="1"/>
   <place id="4" name="p1" tokens="1"/>
   <place id="8" name="mem" tokens="1"/>
   <transx id="0" name="t0" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="10" name="t8" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="14" name="t4" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="1" name="t2" Progr="Yes" New="Yes" EFT="   0" LFT="   0" Fir="Yes" class_dest="17"/>
   <transx id="6" name="t6" Progr="No " New="No " EFT="   0" LFT="   0" Fir="No "/>
 </class>
 <class level="0" id="15" >
   <place id="0" name="p0" tokens="1"/>
   <place id="7" name="p6" tokens="1"/>
   <transx id="7" name="t7" Progr="Yes" New="No " EFT="   1" LFT="   2" Fir="Yes" class_dest="18"/>
   <transx id="10" name="t8" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="14" name="t4" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="0" name="t0" Progr="Yes" New="Yes" EFT="  10" LFT="  10" Fir="No "/>
   <transx id="9" name="t1" Progr="No " New="Yes" EFT="   0" LFT="   0" Fir="No "/>
 </class>
 <class level="0" id="16" >
   <place id="5" name="p4" tokens="1"/>
   <place id="8" name="mem" tokens="1"/>
   <transx id="5" name="t5" Progr="Yes" New="No " EFT="   0" LFT="   0" Fir="Yes" class_dest="19"/>
   <transx id="0" name="t0" Progr="Yes" New="No " EFT="   8" LFT="   9" Fir="No "/>
   <transx id="10" name="t8" Progr="Yes" New="No " EFT="   8" LFT="   9" Fir="No "/>
   <transx id="14" name="t4" Progr="Yes" New="No " EFT="   8" LFT="   9" Fir="No "/>
   <binding idtrans1="10" idtrans2="0" EFT="   0" LFT="   0"/>
   <binding idtrans1="14" idtrans2="0" EFT="   0" LFT="   0"/>
   <binding idtrans1="14" idtrans2="10" EFT="   0" LFT="   0"/>
 </class>
 <class level="0" id="17" >
   <place id="6" name="p5" tokens="1"/>
   <place id="10" name="p2" tokens="1"/>
   <transx id="0" name="t0" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="10" name="t8" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="14" name="t4" Progr="Yes" New="No " EFT="  10" LFT="  10" Fir="No "/>
   <transx id="11" name="t3" Progr="Yes" New="Yes" EFT="   1" LFT="   2" Fir="Yes" class_dest="19"/>
 </class>
 <class level="0" id="18" >
   <place id="0" name="p0" tokens="1"/>
   <place id="8" name="mem" tokens="1"/>
